SELECT TOP 9999999 Er_Mpe_Id event_id, Location_Name_Rln do_name, Tracked_Event_Cd event_cd, User_Id user_id, Device_Id device_id,
event_dttm event_dttm,
scan_dttm scan_dttm,
route_id route_id,
Route_Walk_Num route_walk_num,
Scanlocation_Longitude longitude,
Scanlocation_Latitude latitude,
Delivery_Postcode postcode,
COALESCE(a.Unique_Item_ID, UPU_Tracking_Num, One_D_Barcode) barcode,
Delivery_Point_Postcode dp_postcode,
Delivery_Point dp
FROM EDW_SCVER_BO_VIEWS.v_base_mpe a
--LEFT OUTER
JOIN EDW_SCVER_CODA_ACCS_VIEWS.v_base_pre_adv_item_detail b ON a.Unique_Item_Id = b.Unique_Item_Id
INNER JOIN EDW_SCVER_BO_VIEWS.v_location l ON a.LOCATION_ID = l.LOCATION_ID
WHERE a.Tracked_Event_Cd LIKE 'EVK%'
AND a.Tracked_Event_Cd <>  'EVKLC'
AND a.Tracked_Event_Cd <>  'EVKLS'
AND do_name IN (
'Abingdon DO',
'Alloa DO',
'Andover DO',
'Ashtead DO',
'Ballymena DO',
'Banbury DO',
'Barnsley DO',
'Bearsden DO',
'Belfast BT15 DO',
'Berkhamsted DO',
'Bilston DO',
'Blackpool DO',
'Bracknell DO',
'Bridgwater DO',
'Bristol South DO',
'Bude DO',
'Burton On Trent DO',
'Bury St Edmunds DO',
'Cambridge DO',
'Cardiff North DO',
'Chelmsford DO',
'Chester DO',
'Clacton On Sea DO',
'Colchester DO',
'Coventry North DO',
'Crewkerne DO',
'Dalkeith DO',
'Deptford DO',
'Dover DO',
'Dundee Central DO',
'East Grinstead DO',
'Edinburgh East DO',
'Enniskillen DO',
'Fareham DO',
'Fordingbridge DO',
'Gainsborough DO',
'Glasgow G13 and G14 DO',
'Glenrothes DO',
'Great Missenden DO',
'Halstead DO',
'Harrow North and South DO',
'Hayes DO',
'Helston DO',
'High Wycombe North DO',
'Holyhead DO',
'Hucknall DO',
'Ilkeston DO',
'Islington DO',
'Iver DO',
'Keswick DO',
'Kingsbridge DO',
'Kittybrewster DO',
'Largs DO',
'Leicester South DO',
'Leyburn DO',
'Liverpool 8 DO',
'Llantwit Major DO',
'Loughborough DO',
'Maidenhead DO',
'Manchester Central DO',
'Marlow DO',
'Mildenhall DO',
'Montrose DO',
'Mount Pleasant EC1 DO',
'Nailsea DO',
'Newark DO',
'Newton Aycliffe DO',
'Northampton NN3A DO',
'Nottingham North DO',
'Orpington DO',
'Oxford East DO',
'Patchway DO',
'Petersfield DO',
'Pontefract DO',
'Portsmouth DO',
'Pulborough DO',
'Reading DO',
'Ringwood DO',
'Royston DO',
'Sandhurst DO',
'Seaton DO',
'Sheffield West DO',
'Skelmersdale DO',
'Slough DO',
'Southend On Sea DO',
'St Albans DO',
'Steyning DO',
'Streatham DO',
'Sutton DO',
'Swindon DO',
'Swindon West DO',
'Tewkesbury DO',
'Tong Road DO',
'Turriff DO',
'Wallingford DO',
'Wembley Lows DO',
'Westhill DO',
'Wimbledon DO',
'Worcester DO',
'Ystalyfera DO'
)
--AND CAST(CAST(Event_Dttm AS TIMESTAMP(0) FORMAT 'YYYY-MM-DDBHH:MI:SSZ')  AS DATE) BETWEEN '2016-01-01' AND '2016-08-31'
--AND CAST(CAST(Event_Dttm AS TIMESTAMP(0) FORMAT 'YYYY-MM-DDBHH:MI:SSZ')  AS DATE) BETWEEN '2016-09-01' AND '2016-09-30';
--AND CAST(CAST(Event_Dttm AS TIMESTAMP(0) FORMAT 'YYYY-MM-DDBHH:MI:SSZ')  AS DATE) BETWEEN '2016-10-01' AND '2016-10-31';
--AND CAST(CAST(Event_Dttm AS TIMESTAMP(0) FORMAT 'YYYY-MM-DDBHH:MI:SSZ')  AS DATE) BETWEEN '2016-11-01' AND '2016-11-30';
AND CAST(CAST(Event_Dttm AS TIMESTAMP(0) FORMAT 'YYYY-MM-DDBHH:MI:SSZ')  AS DATE) BETWEEN '2016-12-01' AND '2016-12-31';